---
- name: Install To-Do App on new web server
  hosts: managed_node
  remote_user: ec2-user
  vars_prompt:

    - name: secret_key
      prompt: What is your key?
      private: no
  
    - name: secret_token
      prompt: What is your token?
      private: no
    
    - name: board_id
      prompt: What is the board ID?
      private: no

    - name: to_do_id
      prompt: What is the ID of the To-Do list?
      private: no

    - name: doing_id
      prompt: What is the ID of the Doing list?
      private: no 

    - name: done_id
      prompt: What is the ID of the Done list?
      private: no
    
  tasks:
   - name: Install git
     yum:
       name: git
       state: latest
     become: yes

   - name: Install Python3
     yum:
       name: python3
       state: latest

   - name: Install Poetry
     ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 - 

   - name: Create todoapp directory
     ansible.builtin.file:
       path: /opt/todoapp
       state: directory
       owner: ec2-user
     become: yes

   - name: Clone the todoapp repo
     ansible.builtin.git:
       repo: https://github.com/jormondroyd27/DevOps-Course-Starter.git
       dest: /opt/todoapp
       version: exercise-4

   - name: Install Poetry dependencies
     ansible.builtin.shell: 
       chdir: /opt/todoapp
       cmd: ~/.local/bin/poetry install

   - name: Template a .env.j2 file to the
     ansible.builtin.template:
       src: ~/ansible/templates/.env.j2
       dest: /opt/todoapp/.env
     become: yes

   - name: copy "todoapp.service" file to "/etc/systemd/system/todoapp.service" on host
     ansible.builtin.copy:
       remote_src: yes
       src: /opt/todoapp/todoapp.service
       dest: /etc/systemd/system/todoapp.service
     become: yes

   - name: Run todoapp on the host
     ansible.builtin.systemd:
       daemon_reload: yes
       name: todoapp.service
       state: restarted
     become: yes