name: Continuous Integration
on: 
  push:
    paths-ignore:
    - "**.md"
  pull_request:
    paths-ignore:
    - "**.md"
jobs: 
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --env-file .env.test todo-app:test
     
  dockerhub:
    name: build and push production image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'module-8'
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to docker
      run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login --username jormondroyd --password-stdin
    
    - name: Docker build
      run: docker build --target production --tag jormondroyd/todo-app .

    - name: Docker push
      run: docker push jormondroyd/todo-app

  heroku:
    name: Heroku deployment
    runs-on: ubuntu-latest
    needs: dockerhub
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "jimbob-todo-app"
        heroku_email: "james.ormondroyd@kpmg.co.uk"
    

 